version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  telemetry_service:
    build: ./telemetry_service
    ports:
      - "9000:9000"

  ml_service:
    build: ./ml_service
    ports:
      - "9100:9100"

volumes:
  pgdata: